#!/usr/bin/env php
<?php

/**
 * Solista - Static website builder
 *
 * @author Giuseppe Spataro <https://github.com/gspataro>
 * @version 1.0.0
 */

use GSpataro\Solista\Solista;

require_once __DIR__ . '/vendor/autoload.php';

Solista::run();
